repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # You can change this to the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
